#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Reset the dist folder as we're going to rebuild it
git restore --staged --worktree ./dist/

# If there are unstaged changes, discard them
# and restore them only after this script exits
unstaged_diff="$(git diff)"
if [ ! -z "$unstaged_diff" ]; then
    git restore .
    trap 'git restore . && (echo "$unstaged_diff" | git apply)' EXIT
fi

# Lint and build staged changes
npm run lint -- --max-warnings=0
git add .

npm run build
git add ./dist/
